"""empty message

Revision ID: 4ddd3c328ea8
Revises: aec47e5ba131
Create Date: 2020-05-21 14:27:18.305781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddd3c328ea8'
down_revision = 'aec47e5ba131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movies', 'col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('col', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
