"""empty message

Revision ID: aec47e5ba131
Revises: 
Create Date: 2020-05-21 14:26:52.525926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aec47e5ba131'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Movies', sa.Column('col', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Movies', 'col')
    # ### end Alembic commands ###
